### ISSUE TITLE
NEW-ENVIRON messages incomplete

### ISSUE THREAD

**Issue by atari2600tim** [Odoth/mudslinger#2]
I tried out the demo just now and my game was not accepting any command input, so I couldn't type in a name to log in.  Looking at network traffic, I found that I am getting sent messages like `IAC SB NEW-ENVIRON IS VAR 'CLIENT_NAME' VALUE 'Mudslinger'` `IAC SB NEW-ENVIRON IS VAR 'CLIENT_VERSION' IS '0.2.6'`, and I guess it is waiting for the end of the telnet negotiation messages.

**Comment by Odoth** [comment]
Demo is updated (version 0.2.7). Please try again and confirm fixed. If you do see further issues please provide connection info for the game in question.

**Comment by atari2600tim** [comment]
Seems to work good now

**Comment by Odoth** [comment]
Thanks for the help!
