### ISSUE TITLE
Problem with deploying it

### ISSUE THREAD

**Issue by vprelovac** [Odoth/mudslinger#5]
Thanks for creating this! 

I am trying to host this at http://216.18.205.234, I started the server but it is failing to load other resources (because I do not have any web server there I think?). 

I have just configured and deployed it with 'npm start' as per readme. Any instructions how to fix this would be very welcome.

**Comment by Odoth** [comment]
It seems some of the files were not properly copied to static directory. This should have happened automatically after running `npm install` through the `postinstall.js` script. Try running postinstall manually: `node tools/postinstall.js`.

**Comment by vprelovac** [comment]
Yep that did the trick. You might want to update the readme with it.
